// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.1
// source: fin_service/days_service.proto

package days

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CondicionesIniciales struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Saldo     float64 `protobuf:"fixed64,1,opt,name=saldo,proto3" json:"saldo,omitempty"`
	TasaAnual float64 `protobuf:"fixed64,2,opt,name=tasa_anual,json=tasaAnual,proto3" json:"tasa_anual,omitempty"`
}

func (x *CondicionesIniciales) Reset() {
	*x = CondicionesIniciales{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fin_service_days_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CondicionesIniciales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CondicionesIniciales) ProtoMessage() {}

func (x *CondicionesIniciales) ProtoReflect() protoreflect.Message {
	mi := &file_fin_service_days_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CondicionesIniciales.ProtoReflect.Descriptor instead.
func (*CondicionesIniciales) Descriptor() ([]byte, []int) {
	return file_fin_service_days_service_proto_rawDescGZIP(), []int{0}
}

func (x *CondicionesIniciales) GetSaldo() float64 {
	if x != nil {
		return x.Saldo
	}
	return 0
}

func (x *CondicionesIniciales) GetTasaAnual() float64 {
	if x != nil {
		return x.TasaAnual
	}
	return 0
}

type Dias struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dias int32 `protobuf:"varint,1,opt,name=dias,proto3" json:"dias,omitempty"`
}

func (x *Dias) Reset() {
	*x = Dias{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fin_service_days_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dias) ProtoMessage() {}

func (x *Dias) ProtoReflect() protoreflect.Message {
	mi := &file_fin_service_days_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dias.ProtoReflect.Descriptor instead.
func (*Dias) Descriptor() ([]byte, []int) {
	return file_fin_service_days_service_proto_rawDescGZIP(), []int{1}
}

func (x *Dias) GetDias() int32 {
	if x != nil {
		return x.Dias
	}
	return 0
}

var File_fin_service_days_service_proto protoreflect.FileDescriptor

var file_fin_service_days_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x66, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x61,
	0x79, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x64, 0x61, 0x79, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x4b,
	0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x49, 0x6e, 0x69,
	0x63, 0x69, 0x61, 0x6c, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x61, 0x73, 0x61, 0x5f, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x74, 0x61, 0x73, 0x61, 0x41, 0x6e, 0x75, 0x61, 0x6c, 0x22, 0x1a, 0x0a, 0x04, 0x44,
	0x69, 0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x64, 0x69, 0x61, 0x73, 0x32, 0x51, 0x0a, 0x0c, 0x64, 0x61, 0x79, 0x73, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x61,
	0x79, 0x73, 0x12, 0x22, 0x2e, 0x64, 0x61, 0x79, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73, 0x49, 0x6e, 0x69,
	0x63, 0x69, 0x61, 0x6c, 0x65, 0x73, 0x1a, 0x12, 0x2e, 0x64, 0x61, 0x79, 0x73, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x69, 0x61, 0x73, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x64, 0x61, 0x79, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_fin_service_days_service_proto_rawDescOnce sync.Once
	file_fin_service_days_service_proto_rawDescData = file_fin_service_days_service_proto_rawDesc
)

func file_fin_service_days_service_proto_rawDescGZIP() []byte {
	file_fin_service_days_service_proto_rawDescOnce.Do(func() {
		file_fin_service_days_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_fin_service_days_service_proto_rawDescData)
	})
	return file_fin_service_days_service_proto_rawDescData
}

var file_fin_service_days_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fin_service_days_service_proto_goTypes = []interface{}{
	(*CondicionesIniciales)(nil), // 0: days_service.CondicionesIniciales
	(*Dias)(nil),                 // 1: days_service.Dias
}
var file_fin_service_days_service_proto_depIdxs = []int32{
	0, // 0: days_service.days_service.GetDays:input_type -> days_service.CondicionesIniciales
	1, // 1: days_service.days_service.GetDays:output_type -> days_service.Dias
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fin_service_days_service_proto_init() }
func file_fin_service_days_service_proto_init() {
	if File_fin_service_days_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fin_service_days_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CondicionesIniciales); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fin_service_days_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dias); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fin_service_days_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fin_service_days_service_proto_goTypes,
		DependencyIndexes: file_fin_service_days_service_proto_depIdxs,
		MessageInfos:      file_fin_service_days_service_proto_msgTypes,
	}.Build()
	File_fin_service_days_service_proto = out.File
	file_fin_service_days_service_proto_rawDesc = nil
	file_fin_service_days_service_proto_goTypes = nil
	file_fin_service_days_service_proto_depIdxs = nil
}
